// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzzlixfjazmsasjpqtuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6emxpeGZqYXptc2FzanBxdHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5NjQ5MTMsImV4cCI6MjA1MzU0MDkxM30.zA5we9fROjZDLMrPFYbEhFlyPrIrUxhpbw1RFharA-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);